"""Base revision

Revision ID: 5688b6adaa40
Revises: 
Create Date: 2015-07-19 22:09:24.425652

"""

# revision identifiers, used by Alembic.
revision = '5688b6adaa40'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
